### ISSUE TITLE
ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by luismiguelprs** [jimmywarting/node-domexception#1]
Hi, I'm getting an error from this package in my application.

`ReferenceError: globalThis is not defined\n    at Object.<anonymous> (/var/www/api/node_modules/node-domexception/index.js:3:1)`

I'm using node 10 on this application and some package is importing the node-domexception package.
Can you add support for node 10?

**Comment by jimmywarting** [comment]
hmm, thinking wether or not it's worth fixing... i could technically change `globalThis` to `global`

then again node v10 stop getting new security updates so one option is to update nodejs version. v10 is pretty old now.
the other is to simply do `global.globalThis = global` somewhere

**Comment by luismiguelprs** [comment]
Unfortunately,  update nodejs version is not possible in our project =/.
It would be great if you can add this fix on package... but for now I think that  `global.globalThis = global` resolves the problem...
